config/routes.rb
Bebas::Application.routes.draw do
  devise_for :users
  root :to => 'index#startpage'
  get  '/users' => 'users#index'
  get '/profile/:user' => 'users#show'
  post '/users/search' => 'users#search'
  get '/guestbook' => 'guestbook/messages#index' 
  post '/guestbook' => 'guestbook/messages#create'
  post '/guestbook/:post' => 'guestbook/messages#destroy'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :moderator
      can :update, :all
    elsif user.has_role? :user
      can :read, :all
    end
  end
end

app/models/guestbook.rb
module Guestbook

  class Guestbook < ActiveRecord::Base
    resourcify
    
    validates :message, :presence => true, :length => { :minimum => 5, :maximum => 250 }
  
    include Gravtastic
      gravtastic

  end

end

app/models/news.rb
module News
  class News < ActiveRecord::Base
    
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  
  rolify
  
  after_create :set_role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :login

  validates :login, :presence => true, 
                    :uniqueness => { case_sensitive: false },
                    :length => { :minimum => 3, :maximum => 25 },
                    :format => { :with => /\A[A-Za-z0-9_]+\z/ }

  include Gravtastic
    gravtastic

  private
  def set_role
   add_role :user
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 before_filter :configure_permitted_parameters, if: :devise_controller?
 protect_from_forgery with: :exception
 protected
 def configure_permitted_parameters
 devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:login, :email, :password) }
 end

end

app/controllers/guestbook/messages_controller.rb
module Guestbook

  class MessagesController < ApplicationController

    def index
      @posts = Guestbook.order('id DESC').paginate(:page => params[:page], :per_page => 10) 
    
      respond_to do |format|
        format.html
        format.js
      end

    end

      def create
        @post = Guestbook.new
        @post.message = params[:guestbook][:message]
        @post.time = Time.now
      
        if user_signed_in?
          @post.author = current_user.login
          @post.email = current_user.email
        else
          @post.author = 'Guest'
          @post.email = 'Guest'
        end
      
        respond_to do |format|
          if @post.save
            format.html { redirect_to guestbook_path }
            format.js { redirect_to guestbook_path }
          else
            format.html { render action: "create" }
            format.js { render action: "create" }
          end
        end

      end

      def destroy
        authorize! :update, Guestbook
        respond_to do |format|
          unless params[:post].empty?
            @post = Guestbook.find(params[:post]).destroy
            format.html { redirect_to guestbook_path }
          else
            format.js { render nothing: true }
          end
        end
      end      

    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def startpage
   
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @users = User.order('id DESC').paginate(:page => params[:page], :per_page => 5)
    @q = User.search(params[:q])
  end

  def show
    @user =  User.where(:login => params[:user])

    if @user.count == 0
      redirect_to :action => 'startpage', :controller => 'index'
    else
      @profile_login = params[:user]
    end

  end

  def search
    @q = User.search(params[:q])
    @result = @q.result(distinct: true)
    
      respond_to do |format|
        unless params[:q].blank?
          format.html
          format.js
        else
          format.html { render nothing: true }
          format.js { render nothing: true }
        end
      end
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title, options={})
    content_for(:title, page_title.to_s)
    return content_tag(:h1, page_title, options)
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div data-alert class="alert-box">
      #{sentence}
      #{messages}
    <a href="#" div class="close">&times;</a>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
  
  def validation_errors!(attr)

    if attr.errors.empty?

      return ""

    else

      messages = attr.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
      sentence = I18n.t("errors.messages.not_saved")

      html = <<-HTML
        <div data-alert class="alert-box">
          #{sentence}
          #{messages}
          <a href="#" div class="close">&times;</a>
        </div>
      HTML

      html.html_safe

    end
    
  end 
  
end

app/views/guestbook/messages/_form.html.haml
= form_for :guestbook, remote: true, :method => :post do |f|
  = f.text_area :message
  = f.submit t('helpers.submit.send'), :class => 'button', data: { disable_with: t('helpers.submit.processing') }

app/views/guestbook/messages/create.html.haml
= validation_errors!(@post)

app/views/guestbook/messages/create.js.erb
var data = <%= {
  :tpl => render(:file => 'guestbook/messages/create.html.haml')
}.to_json.html_safe %>;

$('#say_div').html(data.tpl);

app/views/guestbook/messages/index.html.haml
- title t '_guestbook'
.row
  .large-12.columns
    %h4= t '_guestbook'
    %hr
.row
  .large-8.columns
    #say_div
    .panel.secondary.hide-on-phones
      - if @posts.length != 0
        - for post in @posts
          %span.left
          .img
            = image_tag post.gravatar_url(:rating => 'R', :secure => true, :size => 50, :default => 'mm')
          %span.right
            %span.radius.label
              = time_ago_in_words(post.time)
            %br
            - if can? :update, Guestbook
              = link_to '×', { :action => :destroy, :post => post }, :method => :post, remote: true
          - if post.author != 'Guest'
            %a{:href => "/profile/#{post.author}"}
              %strong= post.author
          - else
            %strong Guest
          %br
          = post.message
          %br
          %br
          %hr
        = foundation_paginate @posts
      - else
        = t 'helpers.error.other'
    %ul.breadcrumbs
      %li= link_to t('_index'), root_path
      %li= link_to t('_guestbook'), guestbook_path
  .large-4.columns
    .panel.secondary.hide-on-phones
      %h6= t '_guestbook_create'
      %hr
      = render 'form'

app/views/guestbook/messages/index.js.erb
var data = <%= {
  :tpl => render(:file => 'guestbook/messages/index.html.haml')
}.to_json.html_safe %>;

$('#main_div').html(data.tpl);

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? content_for(:title) : "..."
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags
    
  %body
    %nav.top-bar
      %ul.title-area
        %li.name
          = image_tag ('logo.png')
        %li.toggle-topbar.menu-icon
          %a{:href => "#"}
            %span= t '_menu'
      %section.top-bar-section
        %ul.left
          = render 'shared/links'
        %ul.right
          - if user_signed_in?
            = render 'shared/users'
          - else
            = render 'shared/guests'
    #main_div
      = yield
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/shared/_guests.html.haml
%li.divider
%li= link_to t("_devise_sign_in"), new_user_session_path, :method => :get

%li.divider
%li= link_to t("_devise_sign_up"), new_user_registration_path, :method => :get
  

app/views/shared/_links.html.haml
%li.divider
%li= link_to t("_guestbook"), guestbook_path

%li.divider
%li= link_to t("_users"), users_path

app/views/shared/_users.html.haml
%li.divider
%li= link_to current_user.login

%li.divider
%li= link_to t("_devise_sign_out"), destroy_user_session_path, :method => :delete

app/views/users/_search.html.haml
= search_form_for @q, :url => users_search_path, remote: true, :method => :post do |f|
  = f.text_field :login_cont, :placeholder => t('helpers.placeholder.users_search')
  = f.submit t('helpers.submit.search'), :class => 'button', data: { disable_with: t('helpers.submit.processing') }

app/views/users/index.html.haml
- title t '_users'
.row
  .large-12.columns
    %h4= t '_users'
    %hr
.row
  .large-8.columns
    .panel.secondary.hide-on-phones
      - if @users.length != 0
        - for user in @users
          .img
            = image_tag user.gravatar_url(:rating => 'R', :secure => true, :size => 50, :default => 'mm')
          %strong= link_to user.login, :action => :show, :user => user.login
          %br
          = user.email
          %br
          %br
          %hr
        = foundation_paginate @users
      - else
        = t 'helpers.error.other'
    %ul.breadcrumbs
      %li= link_to t('_index'), root_path
      %li= link_to t('_users'), users_path
  .large-4.columns
    .panel.secondary.hide-on-phones
      = render 'search'
      #search_div

app/views/users/search.html.haml
#result{"data-alert" => ""}
  = t '_users_search'
  %a.close{:div => "", :href => "#"} ×
  %hr
  - unless @result.empty?
    - @result.each do |user|
      .img
        = image_tag user.gravatar_url(:rating => 'R', :secure => true, :size => 30, :default => 'mm')
      %strong= link_to user.login, :action => :show, :user => user.login
      %br
      %small= user.email 
      %br
      %br
  - else
    = t 'helpers.error.search'

app/views/users/search.js.erb
var data = <%= {
  :tpl => render(:file => 'users/search.html.haml')
}.to_json.html_safe %>;

$('#search_div').html(data.tpl);

app/views/users/show.html.haml
- title t '_profile'
.row
  .large-12.columns
    %h4
      = t '_profile'
      = @profile_login
    %hr
.row
  .large-8.columns
    .panel.secondary.hide-on-phones
      - for user in @user
        %span.right
          .img
            = image_tag user.gravatar_url(:rating => 'R', :secure => true, :size => 80, :default => 'mm')
        = t 'activerecord.attributes.user.login'
        = user.login
        %br
        = t 'activerecord.attributes.user.email'
        = user.email
        %br
        = t 'activerecord.attributes.user.sign_in_count'
        = user.sign_in_count
        %br
        = t 'activerecord.attributes.user.last_sign_in_at'
        = user.last_sign_in_at.localize_stamp("1 Jan 1999, 18:12")
        %br
        = t 'activerecord.attributes.user.created_at'
        = user.created_at.localize_stamp("1 Jan 1999, 18:12")
        %br
        = t 'activerecord.attributes.user.roles'
        = user.roles.first.name
    %ul.breadcrumbs
      %li= link_to t('_index'), root_path
      %li= link_to t('_users'), users_path
      %li= link_to params[:user]
  .large-4.columns
    .panel.secondary.hide-on-phones